[phases.setup]
nixPkgs = ["ant", "jdk17", "tomcat9"]

[phases.install]
cmds = [
  "ant dist",
  "mkdir -p /tmp/tomcat/webapps",
  "cp dist/Warehouse.war /tmp/tomcat/webapps/ROOT.war"
]

[start]
cmd = "CATALINA_HOME=/tmp/tomcat /nix/store/*tomcat*/bin/catalina.sh run"

