[phases.setup]
nixPkgs = ["ant", "jdk17", "tomcat9"]

[phases.install]
cmds = [
  "ant dist",
  "mkdir -p webapps logs temp work",
  "cp dist/Warehouse.war webapps/ROOT.war",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh"

